import type { MentorProfile, NewStudentProfile, ResourceItem, UserProfile, CommunityPost } from './types';
import placeholderImages from './placeholder-images.json';

const imageById = (id: string) => placeholderImages.placeholderImages.find((item) => item.id === id)?.imageUrl;

export const currentUser: UserProfile = {
  id: 'main-user',
  name: '张伟',
  email: 'wei.zhang@example.com',
  avatarUrl: imageById('user-avatar'),
  major: '智能感知工程',
  grade: '23级',
  role: 'freshman',
  interests: ['人工智能', '数字教育', 'Web开发'],
  skills: ['Python', 'JavaScript', 'React', '数据整理'],
  supportNeeds: ['入学适应', '竞赛规划', '课程选择建议'],
  canSupportWith: ['AI 工具入门分享', '活动志愿协助'],
  motivation: '希望在平台中找到长期指导，同时逐步成长为能够回馈新生的高年级骨干。',
};

export const defaultNewStudentProfile: NewStudentProfile = {
  name: '王晓明',
  major: '计算机科学',
  academicInterests: ['人工智能', '数据科学'],
  hobbies: ['篮球', '摄影'],
  goals: '尽快适应大学学习节奏，并在大一下学期加入竞赛项目组。',
};

export const seniorMentors: MentorProfile[] = [
  {
    id: 'mentor-1',
    name: '李伟',
    major: '计算机科学',
    academicInterests: ['人工智能', '机器学习', '计算机视觉'],
    hobbies: ['编程', '阅读'],
    experienceSummary: '带过两届新生科研启蒙，熟悉课程规划、实验室入门和竞赛训练路径。',
    availability: '高',
    supportAreas: ['新生科研启蒙', '课程避坑', '实验室入门'],
    mentorBenefits: ['累计朋辈帮扶时长', '沉淀科研带教案例', '提升项目组织能力'],
    style: '结构化指导，适合需要清晰路线的新生。',
  },
  {
    id: 'mentor-2',
    name: '王芳',
    major: '自动化',
    academicInterests: ['控制理论', '机器人学', '项目管理'],
    hobbies: ['徒步', '摄影'],
    experienceSummary: '曾负责学院迎新志愿团队，擅长帮助新生建立学习节奏和社群归属。',
    availability: '中',
    supportAreas: ['入学适应', '社团活动推荐', '志愿项目协作'],
    mentorBenefits: ['形成志愿服务记录', '提升沟通领导力', '扩大跨年级合作网络'],
    style: '陪伴型带教，适合希望快速融入校园的新生。',
  },
  {
    id: 'mentor-3',
    name: '张敏',
    major: '软件工程',
    academicInterests: ['Web开发', '移动应用开发', '产品设计'],
    hobbies: ['音乐', '游戏'],
    experienceSummary: '做过校内平台项目负责人，能把经验转化为模板、文档和项目机会。',
    availability: '高',
    supportAreas: ['项目协作', '前端开发', '作品集准备'],
    mentorBenefits: ['沉淀项目案例', '获得导师型展示素材', '提升跨年级协作效率'],
    style: '项目驱动型，适合希望边做边学的新生。',
  },
  {
    id: 'mentor-4',
    name: '孙秀英',
    major: '数据科学',
    academicInterests: ['数据分析', '大数据', '深度学习'],
    hobbies: ['羽毛球', '旅游'],
    experienceSummary: '长期参与数据竞赛辅导，善于把复杂经验拆成易执行的成长任务。',
    availability: '高',
    supportAreas: ['竞赛入门', '数据分析训练', '学习复盘'],
    mentorBenefits: ['积累带教影响力', '沉淀方法论', '扩大专业社群连接'],
    style: '任务拆解型，适合希望稳步提升的新生。',
  },
  {
    id: 'mentor-5',
    name: '周静',
    major: '物联网工程',
    academicInterests: ['嵌入式系统', '传感器网络', '边缘计算'],
    hobbies: ['电子制作', '爬山'],
    experienceSummary: '喜欢做作品复盘和经验分享，能够帮助新生打通课程到项目的第一步。',
    availability: '中',
    supportAreas: ['硬件项目起步', '比赛作品复盘', '学习资料整理'],
    mentorBenefits: ['形成经验资产库', '提升表达能力', '获得跨专业协作机会'],
    style: '实战经验型，适合动手导向的新生。',
  },
  {
    id: 'mentor-6',
    name: '吴强',
    major: '网络安全',
    academicInterests: ['渗透测试', '密码学', '区块链'],
    hobbies: ['CTF比赛', '科幻小说'],
    experienceSummary: '可为有明确方向的新生提供高强度目标导向辅导，帮助制定提升计划。',
    availability: '低',
    supportAreas: ['方向选择', '比赛路线图', '进阶技能建议'],
    mentorBenefits: ['形成导师荣誉记录', '扩大技术影响力', '筛选长期项目伙伴'],
    style: '目标冲刺型，适合已有明确兴趣的新生。',
  },
];

export const students: UserProfile[] = [
  {
    id: 'student-1',
    name: '陈晨',
    major: '计算机科学',
    grade: '23级',
    role: 'freshman',
    interests: ['游戏开发', '图形学'],
    skills: ['C++', 'Unity'],
    email: 'chen.chen@example.com',
    avatarUrl: imageById('student-1'),
    supportNeeds: ['项目入门', '团队协作'],
    canSupportWith: ['游戏测试', '社区活动参与'],
    motivation: '希望尽快加入一个长期项目团队，积累可展示的实践经历。',
  },
  {
    id: 'student-2',
    name: '刘洋',
    major: '软件工程',
    grade: '23级',
    role: 'freshman',
    interests: ['Web开发', 'DevOps'],
    skills: ['Java', 'Spring', 'Docker'],
    email: 'yang.liu@example.com',
    avatarUrl: imageById('student-2'),
    supportNeeds: ['课程路线', '项目历练'],
    canSupportWith: ['部署实践', '资料整理'],
    motivation: '希望找到能一起做产品和积累比赛经验的学长学姐。',
  },
  {
    id: 'student-3',
    name: '王静',
    major: '智能感知工程',
    grade: '22级',
    role: 'senior',
    interests: ['物联网', '数据分析'],
    skills: ['Python', 'SQL'],
    email: 'jing.wang@example.com',
    avatarUrl: imageById('student-3'),
    supportNeeds: ['带教方法', '活动组织'],
    canSupportWith: ['学习陪伴', '考试复习经验'],
    motivation: '希望通过带教新生把自己的复习方法和时间管理经验沉淀下来。',
  },
  {
    id: 'student-4',
    name: '李涛',
    major: '数据科学',
    grade: '22级',
    role: 'senior',
    interests: ['机器学习', '自然语言处理'],
    skills: ['Python', 'TensorFlow'],
    email: 'tao.li@example.com',
    avatarUrl: imageById('student-4'),
    supportNeeds: ['带教记录整理', '分享活动组织'],
    canSupportWith: ['保研经验', 'AI Lab 申请建议'],
    motivation: '希望让自己的科研申请经验形成可复用的校内经验库。',
  },
  {
    id: 'student-5',
    name: '张悦',
    major: '自动化',
    grade: '23级',
    role: 'freshman',
    interests: ['机器人', '控制系统'],
    skills: ['C', 'MATLAB'],
    email: 'yue.zhang@example.com',
    avatarUrl: imageById('student-5'),
    supportNeeds: ['实验室选择', '竞赛入门'],
    canSupportWith: ['志愿活动执行'],
    motivation: '想先完成适应，再找到能长期跟进的学长学姐。',
  },
  {
    id: 'student-6',
    name: '徐峰',
    major: '网络工程',
    grade: '22级',
    role: 'senior',
    interests: ['网络安全', '云计算'],
    skills: ['Linux', 'Bash'],
    email: 'feng.xu@example.com',
    avatarUrl: imageById('student-6'),
    supportNeeds: ['团队招募', '经验传播'],
    canSupportWith: ['CTF 路线建议', '服务器部署'],
    motivation: '希望通过平台找到愿意长期打比赛和做项目的低年级伙伴。',
  },
  {
    id: 'student-7',
    name: '黄娟',
    major: '计算机科学',
    grade: '23级',
    role: 'freshman',
    interests: ['移动开发', 'UI/UX设计'],
    skills: ['Swift', 'Figma'],
    email: 'juan.huang@example.com',
    avatarUrl: imageById('student-7'),
    supportNeeds: ['项目展示', '课程取舍'],
    canSupportWith: ['界面设计协助'],
    motivation: '希望通过跨年级合作把设计能力真正用到项目里。',
  },
  {
    id: 'student-8',
    name: '马超',
    major: '软件工程',
    grade: '22级',
    role: 'senior',
    interests: ['后端开发', '数据库'],
    skills: ['Go', 'PostgreSQL'],
    email: 'chao.ma@example.com',
    avatarUrl: imageById('student-8'),
    supportNeeds: ['经验沉淀', '项目协作者招募'],
    canSupportWith: ['后端架构答疑', '接口设计'],
    motivation: '希望通过辅导新生，把自己的项目经验整理成可复用模板。',
  },
  {
    id: 'student-9',
    name: '胡琳',
    major: '数据科学',
    grade: '23级',
    role: 'freshman',
    interests: ['数据可视化', '商业智能'],
    skills: ['R', 'Tableau'],
    email: 'lin.hu@example.com',
    avatarUrl: imageById('student-9'),
    supportNeeds: ['数据竞赛入门', '时间管理'],
    canSupportWith: ['可视化志愿协作'],
    motivation: '希望快速看懂学长学姐走过的路径，少踩弯路。',
  },
  {
    id: 'student-10',
    name: '林芳',
    major: '智能感知工程',
    grade: '22级',
    role: 'senior',
    interests: ['边缘计算', '嵌入式AI'],
    skills: ['Python', 'C++'],
    email: 'fang.lin@example.com',
    avatarUrl: imageById('student-10'),
    supportNeeds: ['活动舞台', '经验展示'],
    canSupportWith: ['硬件项目指导', '课程复盘'],
    motivation: '希望把自己的项目经验变成对新生真正有帮助的实践范例。',
  },
];

export const resources: ResourceItem[] = [
  {
    id: 'res-1',
    title: '新生入学适应清单',
    author: '王芳',
    authorAvatar: imageById('mentor-2'),
    description: '从选课、作息、社团融入到第一学期目标设定，帮助新生快速稳定下来。',
    image: imageById('campus-1'),
    tags: ['入学适应', '成长清单'],
    downloadUrl: 'https://www.coursera.org/learn/learning-how-to-learn',
    category: '新生入门包',
    audience: 'freshman',
    mentorValue: '老生可将迎新经验沉淀为标准化清单。',
    freshmanValue: '新生能在最短时间内建立第一学期行动框架。',
  },
  {
    id: 'res-2',
    title: '实验室与竞赛入门地图',
    author: '李伟',
    authorAvatar: imageById('mentor-1'),
    description: '梳理学院实验室方向、竞赛时间线和准备建议，帮助新生做出更合适的选择。',
    image: imageById('resource-2'),
    tags: ['实验室', '竞赛规划'],
    downloadUrl: 'https://www.coursera.org/learn/algorithms-part1',
    category: '新生入门包',
    audience: 'freshman',
    mentorValue: '老生经验被结构化后更容易复用和传承。',
    freshmanValue: '新生能更快理解不同成长路径的差异。',
  },
  {
    id: 'res-3',
    title: '学长学姐保研申请经验库',
    author: '李涛',
    authorAvatar: imageById('student-4'),
    description: '收录保研准备时间轴、材料清单和面试常见问题，适合作为成长目标参考。',
    image: imageById('resource-3'),
    tags: ['保研', '经验沉淀'],
    downloadUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    category: '学长经验库',
    audience: 'all',
    mentorValue: '老生可形成成果展示和案例证明。',
    freshmanValue: '新生能从前辈路径中明确长期目标。',
  },
  {
    id: 'res-4',
    title: '课程避坑与搭配建议',
    author: '周静',
    authorAvatar: imageById('mentor-5'),
    description: '按学期整理课程难点、推荐组合和常见误区，降低新生试错成本。',
    image: imageById('resource-1'),
    tags: ['课程规划', '学业建议'],
    downloadUrl: 'https://www.coursera.org/learn/front-end-interview-prep',
    category: '学长经验库',
    audience: 'all',
    mentorValue: '老生的复盘会转化为平台长期资产。',
    freshmanValue: '新生能提前规避时间分配和选课失误。',
  },
  {
    id: 'res-5',
    title: '跨年级项目协作模板',
    author: '张敏',
    authorAvatar: imageById('mentor-3'),
    description: '包含项目分工模板、周报模版和协同流程，适合新老生一起做比赛或课程设计。',
    image: imageById('resource-4'),
    tags: ['项目协作', '模板'],
    downloadUrl: 'https://opensource.guide/how-to-contribute/',
    category: '协同工具箱',
    audience: 'all',
    mentorValue: '老生更容易从一次次带教中形成方法论。',
    freshmanValue: '新生能更顺畅地参与真实项目协作。',
  },
  {
    id: 'res-6',
    title: '朋辈帮扶记录与成长证明样例',
    author: '徐峰',
    authorAvatar: imageById('student-6'),
    description: '展示老生如何记录帮扶过程、志愿时长和项目成果，突出平台对高年级的实际价值。',
    image: imageById('campus-1'),
    tags: ['帮扶记录', '成长证明'],
    downloadUrl: 'https://www.coursera.org/learn/project-management-foundations',
    category: '协同工具箱',
    audience: 'senior',
    mentorValue: '老生可把带教经历转化为个人成长证明。',
    freshmanValue: '新生能看到高年级参与后的正向激励。',
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: 'post-1',
    author: '陈晨',
    authorId: 'student-1',
    authorAvatar: imageById('student-1'),
    title: '刚入学想找一位愿意带我做第一次课程项目的学长',
    content: '我是 23 级新生，最近刚开始接触课程设计，最担心的是不知道如何分解任务和安排时间。希望能找到一位做过类似项目的学长学姐，带我把第一次项目完整走一遍。',
    tags: ['新生求助', '课程项目'],
    postType: 'ask_help',
    audience: 'senior',
    timestamp: '2026-03-09T09:30:00Z',
    likes: 36,
    commentsCount: 12,
  },
  {
    id: 'post-2',
    author: '李涛',
    authorId: 'student-4',
    authorAvatar: imageById('student-4'),
    title: '把我从大一到进 AI Lab 的路线整理成了一份经验清单',
    content: '我把课程安排、竞赛节点、老师沟通和材料准备做成了一份时间轴，希望给低年级同学一个可以照着走的参考，也欢迎其他学长学姐一起补充。',
    tags: ['经验分享', 'AI Lab'],
    postType: 'share_experience',
    audience: 'all',
    timestamp: '2026-03-10T03:10:00Z',
    likes: 82,
    commentsCount: 21,
  },
  {
    id: 'post-3',
    author: '黄娟',
    authorId: 'student-7',
    authorAvatar: imageById('student-7'),
    title: '招募一位学长和两位同级同学一起做校园服务小程序',
    content: '我负责界面设计，希望找一位有项目经验的学长当协作教练，再找两位同级同学一起做落地 demo。这个过程我最想学的是如何从零组织一个靠谱的团队。',
    tags: ['项目招募', '协同实践'],
    postType: 'recruit_partner',
    audience: 'all',
    timestamp: '2026-03-10T11:40:00Z',
    likes: 54,
    commentsCount: 16,
  },
  {
    id: 'post-4',
    author: '王静',
    authorId: 'student-3',
    authorAvatar: imageById('student-3'),
    title: '周末做一次“新生避坑答疑夜”，欢迎把问题提前发上来',
    content: '我和几位 22 级同学准备组织一次跨年级线上答疑，主题包括课程选择、时间管理、竞赛入门和实验室体验。提前留言的问题会整理成长期 FAQ，方便后续更多新生查看。',
    tags: ['活动通知', '答疑夜'],
    postType: 'activity_notice',
    audience: 'freshman',
    timestamp: '2026-03-11T02:20:00Z',
    likes: 61,
    commentsCount: 19,
  },
  {
    id: 'post-5',
    author: '徐峰',
    authorId: 'student-6',
    authorAvatar: imageById('student-6'),
    title: '做学长帮扶以后，我最大的收获其实是表达和组织能力',
    content: '以前我只关注比赛成绩，后来开始带新生做训练计划，才发现“讲明白”和“带着别人一起进步”本身就是一种能力成长。平台如果能把这些过程记录下来，对老生也很有价值。',
    tags: ['老生收益', '经验分享'],
    postType: 'share_experience',
    audience: 'all',
    timestamp: '2026-03-11T07:15:00Z',
    likes: 73,
    commentsCount: 24,
  },
  {
    id: 'post-6',
    author: '张悦',
    authorId: 'student-5',
    authorAvatar: imageById('student-5'),
    title: '求一份“怎么判断自己适合哪个实验室”的前辈建议',
    content: '我对机器人和控制系统都感兴趣，但不知道该怎么选方向。希望听听学长学姐是如何判断自己适合什么，以及刚开始要做哪些准备。',
    tags: ['方向选择', '新生求助'],
    postType: 'ask_help',
    audience: 'senior',
    timestamp: '2026-03-11T10:05:00Z',
    likes: 28,
    commentsCount: 9,
  },
];

export const platformMetrics = [
  { label: '结对样例', value: '18 组', detail: '覆盖入学适应、课程指导、项目协作三类场景' },
  { label: '经验资源', value: '36 份', detail: '已整理为清单、模板、路线图和活动记录' },
  { label: '老生参与收益', value: '3 类', detail: '帮扶记录、能力证明、项目协作机会同步沉淀' },
];

export const collaborationSteps = [
  '注册画像，明确自己当前阶段与最想解决的问题。',
  '系统根据兴趣、专业、目标和帮扶方向完成结对推荐。',
  '在社区和资源中心建立互动，围绕真实任务展开协作。',
  '通过成长顾问和阶段反馈，持续调整任务和帮扶节奏。',
  '把经验、案例和成果沉淀成可复用的校内资源。',
];

export const freshmanBenefits = [
  '更快适应课程节奏与校园生活',
  '获得清晰的成长路径和资源导航',
  '通过真实项目和活动建立归属感',
];

export const seniorBenefits = [
  '沉淀志愿服务与朋辈帮扶记录',
  '形成个人经验案例和展示成果',
  '提升沟通、组织与领导力',
  '更高效地找到跨年级项目伙伴',
];

export const dashboardTasks = [
  '完善个人画像，明确本学期最需要的三项支持。',
  '参加一次跨年级答疑或经验分享活动。',
  '从经验资源库中收藏两份可直接执行的模板。',
];
